config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "jobs"

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resource :settings, only: %i[edit update]

  resources :transactions do
    match "search" => "transactions#search", on: :collection, via: [ :get, :post ], as: :search
  end

  namespace :transactions do
    resources :categories
  end

  resources :accounts, shallow: true do
    post :sync, on: :member
    resources :valuations
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/transaction/category.rb
class Transaction::Category < ApplicationRecord
  has_many :transactions, dependent: :nullify
  belongs_to :family

  validates :name, :color, :family, presence: true

  before_update :clear_internal_category, if: :name_changed?

  COLORS = %w[#e99537 #4da568 #6471eb #db5a54 #df4e92 #c44fe9 #eb5429 #61c9ea #805dee #6ad28a]

  UNCATEGORIZED_COLOR = "#737373"

  DEFAULT_CATEGORIES = [
    { internal_category: "income", color: COLORS[0] },
    { internal_category: "food_and_drink", color: COLORS[1] },
    { internal_category: "entertainment", color: COLORS[2] },
    { internal_category: "personal_care", color: COLORS[3] },
    { internal_category: "general_services", color: COLORS[4] },
    { internal_category: "auto_and_transport", color: COLORS[5] },
    { internal_category: "rent_and_utilities", color: COLORS[6] },
    { internal_category: "home_improvement", color: COLORS[7] }
  ]

  def self.ransackable_attributes(auth_object = nil)
    %w[name id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[]
  end

  def self.create_default_categories(family)
    if family.transaction_categories.size > 0
      raise ArgumentError, "Family already has some categories"
    end

    family_id = family.id
    categories = self::DEFAULT_CATEGORIES.map { |c| {
      name: I18n.t("transaction.default_category.#{c[:internal_category]}"),
      internal_category: c[:internal_category],
      color: c[:color],
      family_id:
    } }
    self.insert_all(categories)
  end

  private

  def clear_internal_category
    self.internal_category = nil
  end
end

app/controllers/transactions/categories_controller.rb
class Transactions::CategoriesController < ApplicationController
  before_action :set_category, only: [ :update, :destroy ]

  def create
    if Current.family.transaction_categories.create(category_params)
      redirect_to transactions_path, notice: t(".success")
    else
      render transactions_path, status: :unprocessable_entity, notice: t(".error")
    end
  end

  def update
    if @category.update(category_params)
      redirect_to transactions_path, notice: t(".success")
    else
      render transactions_path, status: :unprocessable_entity, notice: t(".error")
    end
  end

  def destroy
    @category.destroy!
    redirect_to transactions_path, notice: t(".success")
  end

  private

  def set_category
    @category = Current.family.transaction_categories.find(params[:id])
  end

  def category_params
    params.require(:transaction_category).permit(:name, :name, :color)
  end
end

app/helpers/transactions/categories_helper.rb
module Transactions::CategoriesHelper
end

app/views/transactions/categories/dropdown/_edit.html.erb
<%# locals: (category:) %>
<div class="w-96 text-sm font-semibold leading-6 text-gray-900 bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
  <div class="flex flex-col">
    <%= render partial: "transactions/categories/dropdown/form", locals: { category: } %>
    <hr/>
    <div class="p-1.5 w-full">
      <%= button_to transactions_category_path(category), 
              method: :delete, 
              class: "flex text-sm font-medium items-center gap-2 text-red-600 w-full rounded-lg p-2 hover:bg-gray-100",
              data: { turbo: false } do %>
        <%= lucide_icon("trash-2", class: "w-5 h-5") %> Delete category
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/categories/dropdown/_form.html.erb
<%# locals: (category: nil) %>
<%= form_with url: category ? transactions_category_path(category) : transactions_categories_path, method: category ? :patch : :post, scope: :transaction_category, html: { class: "text-sm font-semibold leading-6 text-gray-900" }, data: { turbo: false } do |form| %>
  <div class="flex flex-col">
    <div class="flex flex-col p-1.5 gap-1.5">
      <div class="relative flex items-center border border-gray-200 rounded-lg">
        <%= form.text_field :name, value: category&.name, placeholder: "Enter Category name", class: "text-sm font-normal placeholder:text-gray-500 h-10 relative pl-6 w-full border-none rounded-lg" %>
      </div>
      <div class="p-2 overflow-x-auto">
        <div data-controller="select" data-select-active-class="bg-gray-200" data-select-selected-value="<%= category&.color || Transaction::Category::COLORS[0] %>">
          <%= form.hidden_field :color, data: { select_target: "input" } %>
          <ul data-select-target="list" class="flex gap-2 items-center">
            <% Transaction::Category::COLORS.each do |color| %>
              <li tabindex="0" data-select-target="option" data-action="click->select#selectOption" data-value="<%= color %>" class="flex shrink-0 justify-center items-center w-6 h-6 cursor-pointer hover:bg-gray-200 rounded-full">
                <div style="background-color: <%= color %>" class="shrink-0 w-4 h-4 rounded-full"></div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <hr/>
    <div class="p-1.5 w-full">
      <%= form.button "Create category", class: "flex text-sm font-medium items-center gap-2 text-gray-900 w-full rounded-lg p-2 hover:bg-gray-100" do %>
        <%= lucide_icon("plus", class: "w-5 h-5") %> <%= category.nil? ? "Create" : "Update" %> category
      <% end %>
    </div>
  </div>
<% end %>

app/views/transactions/categories/dropdown/_row.html.erb
<%# locals: (category:, transaction:) %>
<% is_selected = transaction.category_id == category.id %>
<%= content_tag :div, class: ["filterable-item flex justify-between items-center border-none rounded-lg px-2 py-1 group w-full", { "bg-gray-25": is_selected }], data: { filter_name: category.name } do %>
  <%= button_to transaction_path(transaction, transaction: { category_id: category.id }), method: :patch, class: "flex w-full items-center gap-1.5 cursor-pointer" do %>
    <span class="w-5 h-5">
      <%= lucide_icon("check", class: "w-5 h-5 text-gray-500") if is_selected %>
    </span>
    <%= render partial: "transactions/categories/badge", locals: { name: category.name, color: category.color } %>
  <% end %>
  <div data-controller="menu">
    <button data-menu-target="button" type="button" class="flex items-center justify-center hover:bg-gray-50 w-8 h-8 rounded-lg">
      <%= lucide_icon("more-horizontal", class: "w-5 h-5 text-gray-500") %>
    </button>
    <div data-menu-target="content" class="absolute z-30 hidden w-screen mt-2 max-w-min">
      <%= render partial: "transactions/categories/dropdown/edit", locals: { category: } %>
    </div>
  </div>
<% end %>