config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "jobs"

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resource :settings, only: %i[edit update]

  resources :transactions do
    match "search" => "transactions#search", on: :collection, via: [ :get, :post ], as: :search
  end

  namespace :transactions do
    resources :categories
  end

  resources :accounts, shallow: true do
    post :sync, on: :member
    resources :valuations
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/transaction/category.rb
class Transaction::Category < ApplicationRecord
  has_many :transactions, dependent: :nullify
  belongs_to :family

  validates :name, :color, :family, presence: true

  before_update :clear_internal_category, if: :name_changed?

  COLORS = %w[#e99537 #4da568 #6471eb #db5a54 #df4e92 #c44fe9 #eb5429 #61c9ea #805dee #6ad28a]

  UNCATEGORIZED_COLOR = "#737373"

  DEFAULT_CATEGORIES = [
    { internal_category: "income", color: COLORS[0] },
    { internal_category: "food_and_drink", color: COLORS[1] },
    { internal_category: "entertainment", color: COLORS[2] },
    { internal_category: "personal_care", color: COLORS[3] },
    { internal_category: "general_services", color: COLORS[4] },
    { internal_category: "auto_and_transport", color: COLORS[5] },
    { internal_category: "rent_and_utilities", color: COLORS[6] },
    { internal_category: "home_improvement", color: COLORS[7] }
  ]

  def self.ransackable_attributes(auth_object = nil)
    %w[name id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[]
  end

  def self.create_default_categories(family)
    if family.transaction_categories.size > 0
      raise ArgumentError, "Family already has some categories"
    end

    family_id = family.id
    categories = self::DEFAULT_CATEGORIES.map { |c| {
      name: I18n.t("transaction.default_category.#{c[:internal_category]}"),
      internal_category: c[:internal_category],
      color: c[:color],
      family_id:
    } }
    self.insert_all(categories)
  end

  private

  def clear_internal_category
    self.internal_category = nil
  end
end

app/controllers/transactions/categories_controller.rb
class Transactions::CategoriesController < ApplicationController
  before_action :set_category, only: [ :update, :destroy ]

  def create
    if Current.family.transaction_categories.create(category_params)
      redirect_to transactions_path, notice: t(".success")
    else
      render transactions_path, status: :unprocessable_entity, notice: t(".error")
    end
  end

  def update
    if @category.update(category_params)
      redirect_to transactions_path, notice: t(".success")
    else
      render transactions_path, status: :unprocessable_entity, notice: t(".error")
    end
  end

  def destroy
    @category.destroy!
    redirect_to transactions_path, notice: t(".success")
  end

  private

  def set_category
    @category = Current.family.transaction_categories.find(params[:id])
  end

  def category_params
    params.require(:transaction_category).permit(:name, :name, :color)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  def index
    search_params = session[ransack_session_key] || params[:q]
    @q = Current.family.transactions.ransack(search_params)
    result = @q.result.order(date: :desc)
    @pagy, @transactions = pagy(result, items: 10)
    @totals = {
      count: result.count,
      income: result.inflows.sum(&:amount_money).abs,
      expense: result.outflows.sum(&:amount_money).abs
    }
    @filter_list = Transaction.build_filter_list(search_params, Current.family)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def search
    if params[:clear]
      session.delete(ransack_session_key)
    elsif params[:remove_param]
      current_params = session[ransack_session_key] || {}
      updated_params = delete_search_param(current_params, params[:remove_param], value: params[:remove_param_value])
      session[ransack_session_key] = updated_params
    elsif params[:q]
      session[ransack_session_key] = params[:q]
    end

    index

    respond_to do |format|
      format.html { render :index }
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("transactions_summary", partial: "transactions/summary", locals: { totals: @totals }),
          turbo_stream.replace("transactions_search_form", partial: "transactions/search_form", locals: { q: @q }),
          turbo_stream.replace("transactions_filters", partial: "transactions/filters", locals: { filters: @filter_list }),
          turbo_stream.replace("transactions_list", partial: "transactions/list", locals: { transactions: @transactions, pagy: @pagy })
        ]
      end
    end
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end

  def edit
  end

  def create
    account = Current.family.accounts.find(params[:transaction][:account_id])

    @transaction = account.transactions.build(transaction_params)

    respond_to do |format|
      if @transaction.save
        @transaction.account.sync_later
        format.html { redirect_to transactions_url, notice: t(".success") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        @transaction.account.sync_later

        format.html { redirect_to transaction_url(@transaction), notice: t(".success") }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("notification-tray", partial: "shared/notification", locals: { type: "success", content: t(".success") }),
            turbo_stream.replace("transaction_#{@transaction.id}", partial: "transactions/transaction", locals: { transaction: @transaction })
          ]
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy!
    @transaction.account.sync_later

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: t(".success") }
    end
  end

  private
    def delete_search_param(params, key, value: nil)
      if value
        params[key]&.delete(value)
        params.delete(key) if params[key].empty? # Remove key if it's empty after deleting value
      else
        params.delete(key)
      end

      params
    end

    def ransack_session_key
      :ransack_transactions_q
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:name, :date, :amount, :currency, :notes, :excluded, :category_id)
    end
end

app/helpers/transactions/categories_helper.rb
module Transactions::CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_filter.html.erb
<%# locals: (filter:) %>
<div class="flex items-center gap-1 text-sm border border-alpha-black-200 rounded-3xl p-1.5">
  <% case filter[:type] %>
  <% when "account" %>
    <div class="flex items-center gap-2">
      <div class="w-5 h-5 bg-blue-600/10 text-xs flex items-center justify-center rounded-full"><%= filter[:value].name[0].upcase %></div>
      <p><%= filter[:value].name %></p>
    </div>
  <% when "category" %>
    <div class="flex items-center gap-2">
      <div class="w-2 h-4 text-xs flex items-center justify-center rounded-full"  style="background-color: <%= filter[:value].color %>"></div>
      <p><%= filter[:value].name %></p>
    </div>
  <% when "search" %>
    <div class="flex items-center gap-2">
      <%= lucide_icon "text", class: "w-5 h-5 text-gray-500" %>
      <p><%= "\"#{filter[:value]}\"".truncate(20) %></p>
    </div>
  <% end %>
  <%= form_with url: search_transactions_path, html: { class: "flex items-center" } do |form| %>
    <%= form.hidden_field :remove_param, value: filter[:original][:key] %>
    <% if filter[:original][:value] %>
      <%= form.hidden_field :remove_param_value, value: filter[:original][:value] %>
    <% end %>
    <%= form.button type: "submit", class: "hover:text-gray-900" do %>
      <%= lucide_icon "x", class: "w-4 h-4 text-gray-500" %>
    <% end %>
  <% end %>
</div>

app/views/transactions/_filters.html.erb
<%# locals: (filters:) %>
<div>
  <%= turbo_frame_tag "transactions_filters" do %>
    <div class="flex items-center gap-2">
      <% filters.each do |filter| %>
        <%= render partial: "transactions/filter", locals: { filter: filter } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/transactions/_form.html.erb
<%= form_with model: @transaction do |f| %>
  <%= f.collection_select :account_id, Current.family.accounts, :id, :name, { prompt: "Select an Account", label: "Account" } %>
  <%= f.date_field :date, label: "Date" %>
  <%= f.text_field :name, label: "Name", placeholder: "Groceries" %>
  <%= f.money_field :amount_money, label: "Amount" %>
  <%= f.submit %>
<% end %>

app/views/transactions/_list.html.erb
<%# locals: (transactions:, pagy:) %>
<div>
  <%= turbo_frame_tag "transactions_list" do %>
    <% if transactions.empty? %>
      <div class="flex flex-col items-center justify-center py-40">
        <p class="text-gray-500 mb-2">No transactions found</p>
        <p class="text-gray-400 max-w-xs text-center">Try adding a transaction, editing filters or refining your search</p>
      </div>
    <% else %>
      <div class="bg-gray-25 rounded-xl px-5 py-3 text-xs font-medium text-gray-500 flex items-center gap-6 mb-4">
        <div class="w-96">
          <p class="uppercase">transaction</p>
        </div>
        <div class="w-48">
          <p class="uppercase">category</p>
        </div>
        <div class="grow uppercase flex justify-between items-center gap-5 text-xs font-medium text-gray-500">
          <p>account</p>
          <p>amount</p>
        </div>
      </div>
      <div class="space-y-6">
        <% transactions.group_by { |transaction| transaction.date }.each do |date, grouped_transactions| %>
          <%= render partial: "transactions/transaction_group", locals: { date: date, transactions: grouped_transactions } %>
        <% end %>
      </div>
    <% end %>
    <% if pagy.pages > 1 %>
      <nav class="flex items-center justify-center px-4 mt-4 sm:px-0">
        <%= render partial: "transactions/pagination", locals: { pagy: pagy } %>
      </nav>
    <% end %>
  <% end %>
</div>

app/views/transactions/_pagination.html.erb
<!-- start mobile pagination -->
  <div class="flex flex-1 justify-center md:hidden">
    <% if pagy.prev %>
      <%= link_to 'Previous', pagy_url_for(pagy, pagy.prev), class: "relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50" %>
    <% else %>
      <div class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-200" >Previous</div>
    <% end %>

    <% if pagy.next %>
      <%= link_to 'Next', pagy_url_for(pagy, pagy.next), class: "relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50" %>
    <% else %>
      <div class="relative ml-3  inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-200" >Next</div>
    <% end %>
  </div>
<!-- end mobile pagination -->

<!-- start desktop pagination -->
<div class="hidden md:-mt-px md:flex">
  <div>
    <% if pagy.prev %>
      <%= link_to pagy_url_for(pagy, pagy.prev), class: "inline-flex items-center  px-3 py-3 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700" do %>
        <%= lucide_icon("chevron-left", class: "w-5 h-5 text-gray-500") %>
      <% end %>
    <% else %>
      <div class="inline-flex items-center px-3 py-3 text-sm font-medium hover:border-gray-300" >
        <%= lucide_icon("chevron-left", class: "w-5 h-5 text-gray-200") %>
      </div>
    <% end %>
  </div>
  <div class="bg-gray-25 rounded-xl">
    <% pagy.series.each do |series_item| %>
      <% if series_item.is_a?(Integer) %>
        <%= link_to pagy_url_for(pagy, series_item), class: "inline-flex items-center  px-3 py-3 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700" do %>
          <%= series_item %>
        <% end %>
      <% elsif series_item.is_a?(String) %>
        <%= link_to pagy_url_for(pagy, series_item), class: "shadow-lg ring-2 ring-inset ring-gray-200 rounded-xl bg-white inline-flex items-center m-1 px-4 py-2 text-sm font-medium text-gray-900" do %>
          <%= series_item %>
        <% end %>
      <% elsif series_item == :gap %>
        <span class="inline-flex items-center  px-3 py-3 text-sm font-medium text-gray-500">...</span>
      <% end %>
    <% end %>
  </div>
    <div>
      <% if pagy.next %>
        <%= link_to pagy_url_for(pagy, pagy.next), class: "inline-flex items-center  px-3 py-3 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700" do %>
          <%= lucide_icon("chevron-right", class: "w-5 h-5 text-gray-500") %>
        <% end %>
      <% else %>
        <div class="inline-flex items-center px-3 py-3 text-sm font-medium hover:border-gray-300" >
          <%= lucide_icon("chevron-right", class: "w-5 h-5 text-gray-200") %>
        </div>
      <% end %>
    </div>
</div>
<!-- end desktop pagination -->

app/views/transactions/_search_form.html.erb
<%# locals: (q:) %>
<div>
  <%= turbo_frame_tag "transactions_search_form" do %>
    <%= search_form_for @q, url: search_transactions_path, html: { method: :post, data: { turbo_frame: "transactions_list", "controller": "auto-submit-form" } } do |form| %>
      <div class="flex gap-2 mb-4">
        <div class="grow">
          <%= render partial: "transactions/search_form/search_filter", locals: { form: form } %>
        </div>
        <div data-controller="menu" class="relative">
          <button data-menu-target="button" type="button" class="border border-gray-200 block h-full rounded-lg flex items-center gap-2 px-4">
            <%= lucide_icon("list-filter", class: "w-5 h-5 text-gray-500") %>
            <p class="text-sm font-medium text-gray-900">Filter</p>
          </button>
          <div data-menu-target="content" class="hidden absolute z-10 top-12 right-0 border border-alpha-black-25 bg-white rounded-lg shadow-xs min-w-[450px]">
            <div data-controller="tabs" data-tabs-active-class="border-b-2 border-b-black text-gray-900" data-tabs-default-tab-value="txn-account-filter">
              <div class="flex items-center px-3 text-sm font-medium text-gray-500 gap-4 border-b border-b-alpha-black-50">
                <button class="py-2 border-b-2" type="button" data-id="txn-account-filter" data-tabs-target="btn" data-action="tabs#select">Account</button>
                <button class="py-2 border-b-2" type="button" data-id="txn-amount-filter" data-tabs-target="btn" data-action="tabs#select">Amount</button>
                <button class="py-2 border-b-2" type="button" data-id="txn-category-filter" data-tabs-target="btn" data-action="tabs#select">Category</button>
                <button class="py-2 border-b-2" type="button" data-id="txn-merchant-filter" data-tabs-target="btn" data-action="tabs#select">Merchant</button>
              </div>
              <div class="p-2 max-h-[300px] overflow-y-auto">
                <div id="txn-account-filter" data-tabs-target="tab">
                  <%= render partial: "transactions/search_form/account_filter", locals: { form: form } %>
                </div>
                <div id="txn-amount-filter" data-tabs-target="tab">
                  <%= render partial: "transactions/search_form/amount_filter", locals: { form: form } %>
                </div>
                <div id="txn-category-filter" data-tabs-target="tab">
                  <%= render partial: "transactions/search_form/category_filter", locals: { form: form } %>
                </div>
                <div id="txn-merchant-filter" data-tabs-target="tab">
                  <%= render partial: "transactions/search_form/merchant_filter", locals: { form: form } %>
                </div>
              </div>
            </div>
            <div class="text-sm p-3 flex items-center justify-between border-t border-t-alpha-black-50">
              <p class="text-gray-500"><%= q.conditions.reject { |condition| condition.values.any?(&:blank?) }.size %> filters applied</p>
              <%= button_to "Clear all", search_transactions_path(clear: true), method: :post, class: "text-gray-900 font-medium", form: { "data-turbo-frame": "transactions_list" } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/transactions/_summary.html.erb
 <%# locals: (totals:) %>
<%= turbo_frame_tag "transactions_summary" do %>
  <div class="grid grid-cols-3 bg-white rounded-xl border border-alpha-black-25 shadow-xs px-4 divide-x divide-alpha-black-100">
    <div class="p-4 space-y-2">
      <p class="text-sm text-gray-500">Total transactions</p>
      <p class="text-gray-900 font-medium text-xl"><%= totals[:count] %></p>
    </div>
    <div class="p-4 space-y-2">
      <p class="text-sm text-gray-500">Income</p>
      <p class="text-gray-900 font-medium text-xl">
        <%= format_money totals[:income] %>
      </p>
    </div>
    <div class="p-4 space-y-2">
      <p class="text-sm text-gray-500">Expenses</p>
      <p class="text-gray-900 font-medium text-xl">
        <%= format_money totals[:expense] %>
      </p>
    </div>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<%= turbo_frame_tag dom_id(transaction), class:"text-gray-900 flex items-center gap-6 py-4 text-sm font-medium px-4" do %>
  <%= link_to transaction_path(transaction), data: { turbo_frame: "modal" }, class: "group", id: dom_id(transaction) do %>
    <div class="w-96 flex items-center gap-2">
      <div class="w-8 h-8 flex items-center justify-center rounded-full bg-gray-600/5 text-gray-600"><%= transaction.name[0].upcase %></div>
      <p class="text-gray-900 group-hover:underline group-hover:text-gray-800"><%= transaction.name %></p>
    </div>
  <% end %>
  <div class="w-48">
    <%= render partial: "transactions/categories/menu", locals: { transaction: } %>
  </div>
  <div>
    <p><%= transaction.account.name %></p>
  </div>
  <div class="ml-auto">
    <p class="<%= transaction.amount < 0 ? "text-green-600" : "" %>"><%= format_money -transaction.amount_money %></p>
  </div>
<% end %>

app/views/transactions/_transaction_group.html.erb
<%# locals: (date:, transactions:) %>
<div class="bg-gray-25 rounded-xl p-1">
  <div class="py-2 px-4 flex items-center justify-between font-medium text-xs text-gray-500">
    <h4><%= date.strftime('%b %d, %Y') %> &middot; <%= transactions.size %></h4>
    <span><%= format_money -transactions.sum(&:amount_money) %></span>
  </div>
  <div class="bg-white shadow-xs rounded-md border border-alpha-black-25 divide-y divide-alpha-black-50">
    <%= render partial: "transactions/transaction", collection: transactions %>
  </div>
</div>

app/views/transactions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing transaction</h1>

  <%= render "form", transaction: @transaction %>

  <%= link_to "Show this transaction", @transaction, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to transactions", transactions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/transactions/index.html.erb
<div class="space-y-4">
  <div class="flex justify-between items-center text-gray-900 font-medium">
    <h1 class="text-xl">Transactions</h1>
    <div class="flex items-center gap-5">
      <div class="flex items-center gap-2">
        <%= link_to new_transaction_path, class: "rounded-lg bg-gray-900 text-white flex items-center gap-1 justify-center hover:bg-gray-700 px-3 py-2" do %>
          <%= lucide_icon("plus", class: "w-5 h-5") %>
          <p>New transaction</p>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <%= render partial: "transactions/summary", locals: { totals: @totals } %>
  </div>
  <div id="transactions" class="bg-white rounded-xl border border-alpha-black-25 shadow-xs p-4 space-y-4">
    <%= render partial: "transactions/search_form", locals: { q: @q } %>
    <%= render partial: "transactions/filters", locals: { filters: @filter_list } %>
    <%= render partial: "transactions/list", locals: { transactions: @transactions, pagy: @pagy } %>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl mb-4">New transaction</h1>
  <%= render "form", transaction: @transaction %>
</div>
<div class="flex justify-center">
  <%= link_to "Back to transactions", transactions_path, class: "mt-8 underline text-lg font-bold" %>
</div>

app/views/transactions/show.html.erb
<%= sidebar_modal do %>
  <h3 class="font-medium mb-1">
    <span class="text-2xl"><%=format_money @transaction.amount_money %></span>
    <span class="text-lg text-gray-500"><%= @transaction.currency %></span>
  </h3>
  <span class="text-sm text-gray-500"><%= @transaction.date.strftime("%A %d %B") %></span>
  <%= form_with model: @transaction, html: {data: {controller: "auto-submit-form"}} do |f| %>
    <details class="group" open>
      <summary class="list-none bg-gray-25 rounded-xl py-1 mt-4 group-open:mb-2">
        <div class="py-2 px-[11px] flex items-center justify-between font-medium text-xs text-gray-500">
          Overview
          <%= lucide_icon("chevron-down", class: "hidden group-open:block text-gray-500 w-5 h-5") %>
          <%= lucide_icon("chevron-right", class: "group-open:hidden text-gray-500 w-5 h-5") %>
        </div>
      </summary>
      <%= f.date_field :date, label: "Date", "data-auto-submit-form-target": "auto" %>
      <div class="h-2"></div>
      <%= f.collection_select :account_id, Current.family.accounts, :id, :name, { prompt: "Select an Account", label: "Account", class: "text-gray-400" }, {class: "form-field__input cursor-not-allowed text-gray-400", disabled: "disabled"} %>
    </details>
    <details class="group" open>
      <summary class="list-none bg-gray-25 rounded-xl py-1 mt-6 group-open:mb-2">
        <div class="py-2 px-[11px] flex items-center justify-between font-medium text-xs text-gray-500">
          Description
          <%= lucide_icon("chevron-down", class: "hidden group-open:block text-gray-500 w-5 h-5") %>
          <%= lucide_icon("chevron-right", class: "group-open:hidden text-gray-500 w-5 h-5") %>
        </div>
      </summary>
      <%= f.text_field :name, label: "Name", "data-auto-submit-form-target": "auto" %>
    </details>
    <details class="group" open>
      <summary class="list-none bg-gray-25 rounded-xl py-1 mt-6 group-open:mb-2">
        <div class="py-2 px-[11px] flex items-center justify-between font-medium text-xs text-gray-500">
          <span>Settings</span>
          <%= lucide_icon("chevron-down", class: "hidden group-open:block text-gray-500 w-5 h-5") %>
          <%= lucide_icon("chevron-right", class: "group-open:hidden text-gray-500 w-5 h-5") %>
        </div>
      </summary>
      <label class="flex items-center cursor-pointer justify-between mx-3">
        <%= f.check_box :excluded, class: "sr-only peer", "data-auto-submit-form-target": "auto" %>
        <div class="flex flex-col justify-center text-sm w-[340px] py-3">
          <span class="text-gray-900 mb-1">Exclude from analytics</span>
          <span class="text-gray-500">This excludes the transaction from any in-app features or analytics.</span>
        </div>
        <div class="relative w-9 h-5 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-100 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-4 after:w-4 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
      </label>
    </details>
    <details class="group" open>
      <summary class="list-none bg-gray-25 rounded-xl py-1 mt-6 mb-2">
        <div class="py-2 px-[11px] flex items-center justify-between font-medium text-xs text-gray-500">
          <span>Additional</span>
          <%= lucide_icon("chevron-down", class: "hidden group-open:block text-gray-500 w-5 h-5") %>
          <%= lucide_icon("chevron-right", class: "group-open:hidden text-gray-500 w-5 h-5") %>
        </div>
      </summary>
      <%= f.text_area :notes, label: "Notes", placeholder: "Enter a note", "data-auto-submit-form-target": "auto" %>
    </details>
  <% end %>
<% end %>