config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "jobs"

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resource :settings, only: %i[edit update]

  resources :transactions do
    match "search" => "transactions#search", on: :collection, via: [ :get, :post ], as: :search
  end

  namespace :transactions do
    resources :categories
  end

  resources :accounts, shallow: true do
    post :sync, on: :member
    resources :valuations
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/account.rb
class Account < ApplicationRecord
  include Syncable
  include Monetizable

  validates :family, presence: true

  broadcasts_refreshes
  belongs_to :family
  has_many :balances, dependent: :destroy
  has_many :valuations, dependent: :destroy
  has_many :transactions, dependent: :destroy

  monetize :balance

  enum :status, { ok: "ok", syncing: "syncing", error: "error" }, validate: true

  scope :active, -> { where(is_active: true) }
  scope :assets, -> { where(classification: "asset") }
  scope :liabilities, -> { where(classification: "liability") }

  delegated_type :accountable, types: Accountable::TYPES, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    %w[name id]
  end

  def balance_on(date)
    balances.where("date <= ?", date).order(date: :desc).first&.balance
  end

  # e.g. Wise, Revolut accounts that have transactions in multiple currencies
  def multi_currency?
    currencies = [ valuations.pluck(:currency), transactions.pluck(:currency) ].flatten.uniq
    currencies.count > 1
  end

  # e.g. Accounts denominated in currency other than family currency
  def foreign_currency?
    currency != family.currency
  end

  def self.by_provider
    # TODO: When 3rd party providers are supported, dynamically load all providers and their accounts
    [ { name: "Manual accounts", accounts: all.order(balance: :desc).group_by(&:accountable_type) } ]
  end

  def self.some_syncing?
    exists?(status: "syncing")
  end


  def series(period: Period.all, currency: self.currency)
    balance_series = balances.in_period(period).where(currency: Money::Currency.new(currency).iso_code)

    if balance_series.empty? && period.date_range.end == Date.current
      converted_balance = balance_money.exchange_to(currency)
      if converted_balance
        TimeSeries.new([ { date: Date.current, value: converted_balance } ])
      else
        TimeSeries.new([])
      end
    else
      TimeSeries.from_collection(balance_series, :balance_money)
    end
  end

  def self.by_group(period: Period.all, currency: Money.default_currency)
    grouped_accounts = { assets: ValueGroup.new("Assets", currency), liabilities: ValueGroup.new("Liabilities", currency) }

    Accountable.by_classification.each do |classification, types|
      types.each do |type|
        group = grouped_accounts[classification.to_sym].add_child_group(type, currency)
        Accountable.from_type(type).includes(:account).each do |accountable|
          account = accountable.account
          next unless account

          value_node = group.add_value_node(
            account,
            account.balance_money.exchange_to(currency) || Money.new(0, currency),
            account.series(period: period, currency: currency)
          )
        end
      end
    end

    grouped_accounts
  end
end

app/models/account/balance.rb
class Account::Balance < ApplicationRecord
    include Monetizable

    belongs_to :account
    validates :account, :date, :balance, presence: true
    monetize :balance
    scope :in_period, ->(period) { period.date_range.nil? ? all : where(date: period.date_range) }
end

app/models/account/balance/calculator.rb
class Account::Balance::Calculator
    attr_reader :daily_balances, :errors, :warnings

    @daily_balances = []
    @errors = []
    @warnings = []

    def initialize(account, options = {})
      @account = account
      @calc_start_date = [ options[:calc_start_date], @account.effective_start_date ].compact.max
    end

    def calculate
      prior_balance = implied_start_balance

      calculated_balances = ((@calc_start_date + 1.day)...Date.current).map do |date|
        valuation = normalized_valuations.find { |v| v["date"] == date }

        if valuation
          current_balance = valuation["value"]
        else
          txn_flows = transaction_flows(date)
          current_balance = prior_balance - txn_flows
        end

        prior_balance = current_balance

        { date: date, balance: current_balance, currency: @account.currency, updated_at: Time.current }
      end

      @daily_balances = [
        { date: @calc_start_date, balance: implied_start_balance, currency: @account.currency, updated_at: Time.current },
        *calculated_balances,
        { date: Date.current, balance: @account.balance, currency: @account.currency, updated_at: Time.current } # Last balance must always match "source of truth"
      ]

      if @account.foreign_currency?
        converted_balances = convert_balances_to_family_currency
        @daily_balances.concat(converted_balances)
      end

      self
    end

    private
      def convert_balances_to_family_currency
        rates = ExchangeRate.get_rate_series(
          @account.currency,
          @account.family.currency,
          @calc_start_date..Date.current
        ).to_a

        @daily_balances.map do |balance|
          rate = rates.find { |rate| rate.date == balance[:date] }
          raise "Rate for #{@account.currency} to #{@account.family.currency} on #{balance[:date]} not found" if rate.nil?
          converted_balance = balance[:balance] * rate.rate
          { date: balance[:date], balance: converted_balance, currency: @account.family.currency, updated_at: Time.current }
        end
      end

      # For calculation, all transactions and valuations need to be normalized to the same currency (the account's primary currency)
      def normalize_entries_to_account_currency(entries, value_key)
        entries.map do |entry|
          currency = entry.currency
          date = entry.date
          value = entry.send(value_key)

          if currency != @account.currency
            rate = ExchangeRate.find_by(base_currency: currency, converted_currency: @account.currency, date: date)
            raise "Rate for #{currency} to #{@account.currency} not found" unless rate

            value *= rate.rate
            currency = @account.currency
          end

          entry.attributes.merge(value_key.to_s => value, "currency" => currency)
        end
      end

      def normalized_valuations
        @normalized_valuations ||= normalize_entries_to_account_currency(@account.valuations.where("date >= ?", @calc_start_date).order(:date).select(:date, :value, :currency), :value)
      end

      def normalized_transactions
        @normalized_transactions ||= normalize_entries_to_account_currency(@account.transactions.where("date >= ?", @calc_start_date).order(:date).select(:date, :amount, :currency), :amount)
      end

      def transaction_flows(date)
        flows = normalized_transactions.select { |t| t["date"] == date }.sum { |t| t["amount"] }
        flows *= -1 if @account.classification == "liability"
        flows
      end

      def implied_start_balance
        oldest_valuation_date = normalized_valuations.first&.dig("date")
        oldest_transaction_date = normalized_transactions.first&.dig("date")
        oldest_entry_date = [ oldest_valuation_date, oldest_transaction_date ].compact.min

        if oldest_entry_date == oldest_valuation_date
          oldest_valuation = normalized_valuations.find { |v| v["date"] == oldest_valuation_date }
          oldest_valuation["value"].to_d
        else
          net_transaction_flows = normalized_transactions.sum { |t| t["amount"].to_d }
          net_transaction_flows *= -1 if @account.classification == "liability"
          @account.balance.to_d + net_transaction_flows
        end
      end
end

app/models/account/credit.rb
class Account::Credit < ApplicationRecord
  include Accountable
end

app/models/account/crypto.rb
class Account::Crypto < ApplicationRecord
  include Accountable
end

app/models/account/depository.rb
class Account::Depository < ApplicationRecord
  include Accountable
end

app/models/account/investment.rb
class Account::Investment < ApplicationRecord
  include Accountable

  SUBTYPES = [
    [ "Brokerage", "brokerage" ],
    [ "Pension", "pension" ],
    [ "Retirement", "retirement" ],
    [ "401(k)", "401k" ],
    [ "529 plan", "529_plan" ],
    [ "Health Savings Account", "hsa" ],
    [ "Mutual Fund", "mutual_fund" ],
    [ "Roth IRA", "roth_ira" ],
    [ "Roth 401k", "roth_401k" ],
    [ "Angel", "angel" ]
  ].freeze
end

app/models/account/loan.rb
class Account::Loan < ApplicationRecord
  include Accountable
end

app/models/account/other_asset.rb
class Account::OtherAsset < ApplicationRecord
  include Accountable
end

app/models/account/other_liability.rb
class Account::OtherLiability < ApplicationRecord
  include Accountable
end

app/models/account/property.rb
class Account::Property < ApplicationRecord
  include Accountable
end

app/models/account/syncable.rb
module Account::Syncable
    extend ActiveSupport::Concern

    def sync_later
        AccountSyncJob.perform_later self
    end

    def sync
        update!(status: "syncing")

        sync_exchange_rates

        calculator = Account::Balance::Calculator.new(self)
        calculator.calculate
        self.balances.upsert_all(calculator.daily_balances, unique_by: :index_account_balances_on_account_id_date_currency_unique)
        self.balances.where("date < ?", effective_start_date).delete_all
        update!(status: "ok", last_sync_date: Date.today)
    rescue => e
        update!(status: "error")
        Rails.logger.error("Failed to sync account #{id}: #{e.message}")
    end

    def can_sync?
        # Skip account sync if account is not active or the sync process is already running
        return false unless is_active
        return false if syncing?
        # If last_sync_date is blank (i.e. the account has never been synced before) allow syncing
        return true if last_sync_date.blank?

        # If last_sync_date is not today, allow syncing
        last_sync_date != Date.today
    end

    # The earliest date we can calculate a balance for
    def effective_start_date
        first_valuation_date = self.valuations.order(:date).pluck(:date).first
        first_transaction_date = self.transactions.order(:date).pluck(:date).first

        [ first_valuation_date, first_transaction_date&.prev_day ].compact.min || Date.current
    end

    # Finds all the rate pairs that are required to calculate balances for an account and syncs them
    def sync_exchange_rates
        rate_candidates = []

        if multi_currency?
            transactions_in_foreign_currency = self.transactions.where.not(currency: self.currency).pluck(:currency, :date).uniq
            transactions_in_foreign_currency.each do |currency, date|
                rate_candidates << { date: date, from_currency: currency, to_currency: self.currency }
            end
        end

        if foreign_currency?
            (effective_start_date..Date.current).each do |date|
                rate_candidates << { date: date, from_currency: self.currency, to_currency: self.family.currency }
            end
        end

        existing_rates = ExchangeRate.where(
            base_currency: rate_candidates.map { |rc| rc[:from_currency] },
            converted_currency: rate_candidates.map { |rc| rc[:to_currency] },
            date: rate_candidates.map { |rc| rc[:date] }
        ).pluck(:base_currency, :converted_currency, :date)

        # Convert to a set for faster lookup
        existing_rates_set = existing_rates.map { |er| [ er[0], er[1], er[2].to_s ] }.to_set

        rate_candidates.each do |rate_candidate|
            rc_from = rate_candidate[:from_currency]
            rc_to = rate_candidate[:to_currency]
            rc_date = rate_candidate[:date]

            next if existing_rates_set.include?([ rc_from, rc_to, rc_date.to_s ])

            logger.info "Fetching exchange rate from provider for account #{self.name}: #{self.id} (#{rc_from} to #{rc_to} on #{rc_date})"
            rate = ExchangeRate.find_rate_or_fetch from: rc_from, to: rc_to, date: rc_date
            ExchangeRate.create! base_currency: rc_from, converted_currency: rc_to, date: rc_date, rate: rate if rate
        end

        nil
    end
end

app/models/account/vehicle.rb
class Account::Vehicle < ApplicationRecord
  include Accountable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  include Filterable
  before_action :set_account, only: %i[ show update destroy sync ]

  def new
    @account = Account.new(
      balance: nil,
      accountable: Accountable.from_type(params[:type])&.new
    )
  end

  def show
    @balance_series = @account.series(period: @period)
    @valuation_series = @account.valuations.to_series
  end

  def edit
  end

  def update
    if @account.update(account_params.except(:accountable_type))

      @account.sync_later if account_params[:is_active] == "1" && @account.can_sync?

      respond_to do |format|
        format.html { redirect_to accounts_path, notice: t(".success") }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("notification-tray", partial: "shared/notification", locals: { type: "success", content: t(".success") }),
            turbo_stream.replace("account_#{@account.id}", partial: "accounts/account", locals: { account: @account })
          ]
        end
      end
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def create
    @account = Current.family.accounts.build(account_params.except(:accountable_type))
    @account.accountable = Accountable.from_type(account_params[:accountable_type])&.new

    if @account.save
      redirect_to accounts_path, notice: t(".success")
    else
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy!
    redirect_to accounts_path, notice: t(".success")
  end

  def sync
    @account.sync_later if @account.can_sync?

    respond_to do |format|
      format.html { redirect_to account_path(@account), notice: t(".success") }
      format.turbo_stream do
        render turbo_stream: turbo_stream.append("notification-tray", partial: "shared/notification", locals: { type: "success", content: t(".success") })
      end
    end
  end

  private

  def set_account
    @account = Current.family.accounts.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:name, :accountable_type, :balance, :currency, :subtype, :is_active)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def to_accountable_title(accountable)
    accountable.model_name.human
  end

  def accountable_text_class(accountable_type)
    class_mapping(accountable_type)[:text]
  end

  def accountable_bg_class(accountable_type)
    class_mapping(accountable_type)[:bg]
  end

  def accountable_bg_transparent_class(accountable_type)
    class_mapping(accountable_type)[:bg_transparent]
  end

  private

  def class_mapping(accountable_type)
    {
      "Account::Credit" => { text: "text-red-500", bg: "bg-red-500", bg_transparent: "bg-red-500/10" },
      "Account::Loan" => { text: "text-fuchsia-500", bg: "bg-fuchsia-500", bg_transparent: "bg-fuchsia-500/10" },
      "Account::OtherLiability" => { text: "text-gray-500", bg: "bg-gray-500", bg_transparent: "bg-gray-500/10" },
      "Account::Depository" => { text: "text-violet-500", bg: "bg-violet-500", bg_transparent: "bg-violet-500/10" },
      "Account::Investment" => { text: "text-blue-600", bg: "bg-blue-600", bg_transparent: "bg-blue-600/10" },
      "Account::OtherAsset" => { text: "text-green-500", bg: "bg-green-500", bg_transparent: "bg-green-500/10" },
      "Account::Property" => { text: "text-cyan-500", bg: "bg-cyan-500", bg_transparent: "bg-cyan-500/10" },
      "Account::Vehicle" => { text: "text-pink-500", bg: "bg-pink-500", bg_transparent: "bg-pink-500/10" }
    }.fetch(accountable_type, { text: "text-gray-500", bg: "bg-gray-500", bg_transparent: "bg-gray-500/10" })
  end
end

app/views/accounts/_account_history.html.erb
<%# locals: (account:, valuations:) %>
<div class="bg-white space-y-4 p-5 border border-alpha-black-25 rounded-xl shadow-xs">
  <div class="flex justify-between items-center">
    <h3 class="font-medium text-lg">History</h3>
    <%= link_to new_account_valuation_path(account), data: { turbo_frame: dom_id(Valuation.new) }, class: "flex gap-1 font-medium items-center bg-gray-50 text-gray-900 p-2 rounded-lg" do %>
      <%= lucide_icon("plus", class: "w-5 h-5 text-gray-900") %>
      <span class="text-sm">New entry</span>
    <% end %>
  </div>
  <div class="rounded-xl bg-gray-25 p-1">
    <div class="flex flex-col rounded-lg space-y-1">
      <div class="text-xs font-medium text-gray-500 uppercase flex items-center px-4 py-2">
        <div class="w-16">date</div>
        <div class="flex items-center justify-between grow">
          <div></div>
          <div>value</div>
        </div>
        <div class="w-56 text-right">change</div>
        <div class="w-[72px]"></div>
      </div>
      <div class="rounded-lg bg-white border-alpha-black-25 shadow-xs">
        <%= turbo_frame_tag dom_id(Valuation.new) %>
        <%= turbo_frame_tag "valuations_list" do %>
          <%= render partial: "accounts/account_valuation_list", locals: { valuation_series: valuations } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/_account_list.html.erb
<%# locals: (group:) -%>
<% type = Accountable.from_type(group.name) %>
<% if group %>
  <details class="mb-1 text-sm group" data-controller="account-collapse" data-account-collapse-type-value="<%= type %>">
    <summary class="flex gap-4 px-3 py-2 items-center w-full rounded-[10px] font-medium hover:bg-gray-100">
      <%= lucide_icon("chevron-down", class: "hidden group-open:block text-gray-500 w-5 h-5") %>
      <%= lucide_icon("chevron-right", class: "group-open:hidden text-gray-500 w-5 h-5") %>
      <div class="text-left"><%= type.model_name.human %></div>
      <div class="ml-auto flex flex-col items-end">
        <p class="text-right"><%= format_money group.sum %></p>
      </div>
    </summary>
    <% group.children.each do |account_value_node| %>
      <%= link_to account_path(account_value_node.original), class: "flex items-center w-full gap-3 px-2 py-3 mb-1 hover:bg-gray-100 rounded-[10px]" do %>
        <div>
          <p class="font-medium"><%= account_value_node.name %></p>
          <% if account_value_node.original.subtype %>
            <p class="text-xs text-gray-500"><%= account_value_node.original.subtype&.humanize %></p>
          <% end %>
        </div>
        <p class="ml-auto font-medium"><%= format_money account_value_node.original.balance_money %></p>
      <% end %>
    <% end %>
    <%= link_to new_account_path(step: 'method', type: type.name.demodulize), class: "flex items-center gap-4 px-2 py-3 mb-1 text-gray-500 text-sm font-medium rounded-[10px] hover:bg-gray-100", data: { turbo_frame: "modal" } do %>
      <%= lucide_icon("plus", class: "w-5 h-5") %>
      <p>New <%= type.model_name.human.downcase %></p>
    <% end %>
  </details>
<% end %>

app/views/accounts/_account_type.html.erb
<%= link_to new_account_path(step: 'method', type: type.class.name.demodulize), class: "flex items-center gap-4 w-full text-center focus:outline-none focus:bg-gray-25 border border-transparent focus:border focus:border-gray-200 block px-2 hover:bg-gray-25 rounded-lg p-2" do %>
  <span class="flex w-8 h-8 shrink-0 grow-0 items-center justify-center rounded-lg <%= bg_color %> border border-alpha-black-25">
    <%= lucide_icon(icon, class: "#{text_color} w-5 h-5") %>
  </span>
  <%= type.model_name.human %>
<% end %>

app/views/accounts/_account_valuation_list.html.erb
<%# locals: (valuation_series:) %>
<% valuation_series.values.reverse_each.with_index do |valuation, index| %>
  <% valuation_styles = trend_styles(valuation.trend) %>
  <%= turbo_frame_tag dom_id(valuation.original) do %>
    <div class="p-4 flex items-center">
      <div class="w-16">
        <div class="w-8 h-8 rounded-full p-1.5 flex items-center justify-center <%= valuation_styles[:bg_class] %>">
          <%= lucide_icon(valuation_styles[:icon], class: "w-4 h-4 #{valuation_styles[:text_class]}") %>
        </div>
      </div>
      <div class="flex items-center justify-between grow">
        <div class="text-sm">
          <p><%= valuation.date %></p>
          <%# TODO: Add descriptive name of valuation %>
          <p class="text-gray-500">Manually entered</p>
        </div>
        <div class="flex text-sm font-medium text-right"><%= format_money valuation.value %></div>
      </div>
      <div class="flex w-56 justify-end text-right text-sm font-medium">
        <% if valuation.trend.value == 0 %>
          <span class="text-gray-500">No change</span>
        <% else %>
          <span class="<%= valuation_styles[:text_class] %>"><%= valuation_styles[:symbol] %><%= format_money valuation.trend.value.abs %></span>
          <span class="<%= valuation_styles[:text_class] %>">(<%= lucide_icon(valuation_styles[:icon], class: "w-4 h-4 align-text-bottom inline") %> <%= valuation.trend.percent %>%)</span>
        <% end %>
      </div>
      <div class="relative w-[72px]" data-controller="menu">
        <button 
          data-menu-target="button" 
          class="ml-auto flex items-center justify-center hover:bg-gray-50 w-8 h-8 rounded-lg"
          >
          <%= lucide_icon("more-horizontal", class: "w-5 h-5 text-gray-500") %>
        </button>
        <div 
          data-menu-target="content" 
          class="absolute min-w-[200px] z-10 top-10 right-0 bg-white p-1 rounded-sm shadow-xs border border-alpha-black-25 w-fit"
        >
          <%= link_to edit_valuation_path(valuation.original), 
              class: "flex gap-1 items-center hover:bg-gray-50 rounded-md p-2" do %>
            <%= lucide_icon("pencil-line", class: "w-5 h-5 text-gray-500 shrink-0") %>
            <span class="text-gray-900 text-sm">Edit entry</span>
          <% end %>
          <%= link_to valuation_path(valuation.original), 
              data: { turbo_method: :delete, 
                      turbo_confirm: { title: t('custom_turbo_confirm.history.title'), 
                                       body: t('custom_turbo_confirm.history.body_html'), 
                                       accept: t('custom_turbo_confirm.history.accept') } }, 
              class: "text-red-600 flex gap-1 items-center hover:bg-gray-50 rounded-md p-2" do %>
            <%= lucide_icon("trash-2", class: "w-5 h-5 shrink-0") %>
            <span class="text-sm">Delete entry</span>
          <% end %>
        </div>
      </div>
    </div>
    <% unless index == valuation_series.values.size - 1 %>
      <div class="h-px bg-alpha-black-50 ml-20 mr-4"></div>
    <% end %>
  <% end %>
<% end %>

app/views/accounts/_entry_method.html.erb
<% if local_assigns[:disabled] && disabled %>
  <span class="flex items-center w-full gap-4 p-2 px-2 text-center border border-transparent rounded-lg cursor-not-allowed focus:outline-none focus:bg-gray-50 focus:border focus:border-gray-200 hover:bg-gray-50">
    <span class="flex w-8 h-8 shrink-0 grow-0 items-center justify-center rounded-lg bg-alpha-black-50 shadow-[inset_0_0_0_1px_rgba(0,0,0,0.02)]">
      <%= lucide_icon(icon, class: "text-gray-500 w-5 h-5") %>
    </span>
    <%= text %>
  </span>
<% else %>
  <%= link_to new_account_path(type: type.class.name.demodulize), class: "flex items-center gap-4 w-full text-center focus:outline-none focus:bg-gray-50 border border-transparent focus:border focus:border-gray-200 px-2 hover:bg-gray-50 rounded-lg p-2" do %>
    <span class="flex w-8 h-8 shrink-0 grow-0 items-center justify-center rounded-lg bg-alpha-black-50 shadow-[inset_0_0_0_1px_rgba(0,0,0,0.02)]">
      <%= lucide_icon(icon, class: "text-gray-500 w-5 h-5") %>
    </span>
    <%= text %>
  <% end %>
<% end %>

app/views/accounts/_sync_message.html.erb
<%# locals: (is_syncing:) %>
<% if is_syncing %>
  <div class="my-4 px-8 py-4 rounded-lg bg-yellow-500/10 flex items-center justify-between">
    <p class="text-gray-900 text-sm">
      Syncing your account balances.
    </p>
  </div>
<% end %>

app/views/accounts/_transactions.html.erb
<%# locals: (transactions:)%>
<div class="bg-white space-y-4 p-5 border border-alpha-black-25 rounded-xl shadow-xs">
  <div class="flex justify-between items-center">
    <h3 class="font-medium text-lg">Transactions</h3>
    <%= link_to new_transaction_path, class: "flex gap-1 font-medium items-center bg-gray-50 text-gray-900 p-2 rounded-lg" do %>
      <%= lucide_icon("plus", class: "w-5 h-5 text-gray-900") %>
      <span class="text-sm">New transaction</span>
    <% end %>
  </div>
  <% if transactions.empty? %>
    <p class="text-gray-500 py-4">No transactions for this account yet.</p>
  <% else %>
    <div class="space-y-6">
      <% transactions.group_by { |transaction| transaction.date }.each do |date, grouped_transactions| %>
        <%= render partial: "transactions/transaction_group", locals: { date: date, transactions: grouped_transactions } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/accounts/index.html.erb
<div class="space-y-4">
  <div class="flex items-center justify-between">
    <h1 class="text-xl font-medium text-gray-900">Accounts</h1>
    <%= link_to new_account_path, class: "flex text-white text-sm font-medium items-center gap-1 bg-gray-900 rounded-lg p-2", data: { turbo_frame: "modal" } do %>
      <%= lucide_icon("plus", class: "w-5 h-5") %>
      <span><%= t('.new_account') %></span>
    <% end %>
  </div>
  <% if Current.family.accounts.empty? %>
    <div class="flex justify-center items-center h-[800px] text-sm">
      <div class="text-center flex flex-col items-center max-w-[300px]">
        <p class="text-gray-900 mb-1 font-medium">No accounts yet</p>
        <p class="text-gray-500 mb-4">Add an account either via connection, importing or entering manually.</p>
        <%= link_to new_account_path, class: "w-fit flex text-white text-sm font-medium items-center gap-1 bg-gray-900 rounded-lg p-2", data: { turbo_frame: "modal" } do %>
          <%= lucide_icon("plus", class: "w-5 h-5") %>
          <span><%= t('.new_account') %></span>
        <% end %>
      </div>
    </div>
  <% else %>
    <div>
      <% Current.family.accounts.by_provider.each do |item| %>
        <details class="bg-white group p-4 border border-alpha-black-25 shadow-xs rounded-xl">
          <summary class="flex items-center gap-2">
            <%= lucide_icon("chevron-down", class: "hidden group-open:block w-5 h-5 text-gray-500") %>
            <%= lucide_icon("chevron-right", class: "group-open:hidden w-5 h-5 text-gray-500") %>
            <% if item[:name] == "Manual accounts" %>
              <div class="flex items-center justify-center h-8 w-8 rounded-full bg-black/5">
                <%= lucide_icon("folder-pen", class: "w-5 h-5 text-gray-500") %>
              </div>
            <% end %>
            <span class="text-sm font-medium text-gray-900">
              <%= item[:name] %>
            </span>
          </summary>
          <div class="space-y-4 mt-4">
            <% item[:accounts].each do |group, accounts| %>
              <div class="bg-gray-25 p-1 rounded-xl">
                <div class="flex items-center px-4 py-2 text-xs font-medium text-gray-500">
                  <p><%= to_accountable_title(Accountable.from_type(group)) %></p>
                  <span class="text-gray-400 mx-2">&middot;</span>
                  <p><%= accounts.count %></p>
                  <p class="ml-auto"><%= format_money accounts.sum(&:balance_money)  %></p>
                </div>
                <div class="bg-white">
                  <% accounts.each do |account| %>
                    <%= render account %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </details>
      <% end %>
    </div>
  <% end %>
</div>